/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { Contract, ContractDefinition } from './contract';

export interface LoopData {
	[k: string]: unknown;
}

export interface LoopContractDefinition extends ContractDefinition<LoopData> {}

export interface LoopContract extends Contract<LoopData> {}
